### PR TITLE
Submodule of cumulus-message-adapter with updated tests

### PR DESCRIPTION
**Pull request by FreedomFaighter**
Update AdapterUtilities.java

updated .gitignore with correct path

updated with path to specific classpath and project files

updated downloadFile and GetMessageAdapterEnvironmentVariable

Build script (#1)

* build script added circle removed

* Update build-and-test.yml

added github work command to build script across multiple operating systems (Windows, Ubuntu, and MacOS) and various java versions and openjdk distributions

* Update pom.xml

updated surefire version

* Update build-and-test.yml

* Update README.md

added status badge

* pom file will not account for current java version

added java version for specialized version invocation

* Update pom.xml

added java version info to build system for the task portion of project

* Update build-and-test.yml

added python action for installing during testing phase of script

Updated tests get json response (#3)

* new try block with getJsonResponse

attempts to let the JRE close the connection instead of calling the close method prematurely

* Update AdapterUtilities.java

* Update AdapterUtilities.java (#2)

submodule approach to linking in cumulus message adapter updated tests for use on junit 5

Null test for task

added test for null pointer exception in case no parameter is given PerformFunction of ITask interface is annotated with an Override indicating it is a method implementation of the ITask interface

added TaskLogic and TaskLogicTest

added task test and updated build script

Update build-and-test.yml (#5)

Updated tests parent pom (#6)

* added parent pom file

* Update build-and-test.yml

revert of .circleci directory

### CODE REVIEW

**Comment by FreedomFaighter** [comment]
needs `git filter-branch --tree-filter 'rm -r .classpath .factorypath .project' HEAD`

**Comment by FreedomFaighter** [comment]
@jennyhliu unable to merge for unknown reason due to login prompt on circle ci for security snyk

**Comment by Jkovarik** [comment]
Hello - thanks for your submission!   Unfortunately it doesn't meet https://github.com/nasa/cumulus-message-adapter-java/blob/master/CONTRIBUTING.md - if you'd like to reopen an issue with a concise set of concerns to be addressed  and a PR with changes to address a particular issue, we can review and get back to you.

**Comment by FreedomFaighter** [comment]
@Jkovarik If you would like to provide feedback on the lack of compliance with your CONTRIBUTING message it appears it was written some time ago by a developer no longer involved

**Comment by FreedomFaighter** [comment]
what is the issue for acceptance on this request?

**Pull request closed without merging**
